version: '3.8'

services:
  sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: $SQL_SERVER_PASSWORD
      ACCEPT_EULA: "Y"
    volumes:
      - sql-server-data:/var/opt/mssql

  account-management-api:
    container_name: account-management-api
    build:
      context: .
      dockerfile: ./account-management/Api/Dockerfile
    image: account-management-api
    depends_on:
      - sql-server
    ports:
      - "8443:443"
    environment:
      ASPNETCORE_ENVIRONMENT: "development"
      SQL_SERVER_NAME: "sql-server"
      SQL_SERVER_PASSWORD: $SQL_SERVER_PASSWORD
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/localhost.pfx"
      ASPNETCORE_Kestrel__Certificates__Default__Password: $CERTIFICATE_PASSWORD
      ASPNETCORE_URLS: "https://+"
    volumes:
      - ${HOME}/.aspnet/https:/https

volumes:
  sql-server-data:
