blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/platform/platform/discussions/new/choose
    about: Start a new discussion on our GitHub Community pages
  - name: Browse exisitng discussions
    url: https://github.com/platform/platform/discussions
    about: Visit our GitHub Community pages to view existing discussions (or click Discussions in the menu)
