trigger:
  branches:
    include:
    - main
  paths:
    include:
    - cloud-infrastructure

steps:
- task: AzureCLI@2
  displayName: "Show planed Bicep changes"
  inputs:
    azureSubscription: 'Azure DevOps Shared'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: 'cloud-infrastructure/bicep/shared/config/shared.sh'
    arguments: 'what-if'

- task: CopyFiles@2
  displayName: 'Copy Bicep files to artifacts'
  inputs:
    SourceFolder: cloud-infrastructure/bicep
    TargetFolder: '$(build.artifactstagingdirectory)/cloud-infrastructure/bicep'

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: 'drop'