trigger:
  branches:
    include:
    - main
  paths:
    include:
    - cloud-infrastructure

steps:
- task: AzureCLI@2
  displayName: "Show planed Bicep changes for Shared recources"
  inputs:
    azureSubscription: 'Azure DevOps Shared'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: 'cloud-infrastructure/bicep/shared/config/shared.sh'
    arguments: '--plan'

- task: AzureCLI@2
  displayName: "Show planed Bicep changes for Staging environment"
  inputs:
    azureSubscription: 'Azure DevOps Staging'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: 'cloud-infrastructure/bicep/environment/config/staging.sh'
    arguments: '--plan'

- task: CopyFiles@2
  displayName: 'Copy Bicep files to artifacts'
  inputs:
    SourceFolder: cloud-infrastructure/bicep
    TargetFolder: '$(build.artifactstagingdirectory)/cloud-infrastructure/bicep'

- task: CopyFiles@2
  displayName: 'Copy Terraform files to artifacts'
  inputs:
    SourceFolder: cloud-infrastructure/terraform
    TargetFolder: '$(build.artifactstagingdirectory)/cloud-infrastructure/terraform'

- task: CopyFiles@2
  displayName: 'Copy Release Pipelines files to artifacts'
  inputs:
    SourceFolder: cloud-infrastructure/release-pipelines
    TargetFolder: '$(build.artifactstagingdirectory)/cloud-infrastructure/release-pipelines'

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: 'drop'