trigger:
  branches:
    include:
    - main
  paths:
    include:
    - cloud-infrastructure

steps:
- task: CopyFiles@2
  displayName: 'Copy Terraform files to artifacts'
  inputs:
    SourceFolder: cloud-infrastructure/terraform
    TargetFolder: '$(build.artifactstagingdirectory)/cloud-infrastructure/terraform'

- task: CopyFiles@2
  displayName: 'Copy Release Pipelines files to artifacts'
  inputs:
    SourceFolder: cloud-infrastructure/release-pipelines
    TargetFolder: '$(build.artifactstagingdirectory)/cloud-infrastructure/release-pipelines'

- task: MicrosoftSecurityDevOps@1
  displayName: 'Run Microsoft Security DevOps scanning'
  inputs:
    break: false
    publish: true
    artifactName: 'CodeAnalysisLogs'

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: 'drop'