name: "Azure Infrastructure - Deployment"

on:
  push:
    branches:
      - main
    paths:
      - 'cloud-infrastructure/**'

jobs:
  shared-plan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to the Shared subscription
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_SHARED }}

    - name: Plan changes to Shared resources
      run: bash ./cloud-infrastructure/shared/config/shared.sh --plan

  shared-deploy:
    needs: shared-plan
    runs-on: ubuntu-latest
    environment: 'shared' ## Force a manual approval
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to the Shared subscription
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_SHARED }}

    - name: Deploy Shared resources
      run: bash ./cloud-infrastructure/shared/config/shared.sh --apply

  staging-plan:
    needs: shared-deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to the Staging subscription
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_STAGING }}

    - name: Plan changes to shared Staging resources
      run: bash ./cloud-infrastructure/environment/config/staging.sh --plan

    - name: Plan changes to Staging West Europe cluster
      run: bash ./cloud-infrastructure/cluster/config/staging-west-europe.sh --plan

  staging-environment-deploy:
    needs: staging-plan
    runs-on: ubuntu-latest
    environment: 'staging' ## Force a manual approval
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to the Staging subscription
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_STAGING }}

    - name: Deploy shared Staging resources
      run: bash ./cloud-infrastructure/environment/config/staging.sh --apply

  staging-west-europe-deploy:
    needs: staging-environment-deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to the Staging subscription
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_STAGING }}

    - name: Deploy Staging West Europe cluster
      run: bash ./cloud-infrastructure/cluster/config/staging-west-europe.sh --apply

  production-plan:
    needs: staging-west-europe-deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to the Production subscription
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_PRODUCTION }}

    - name: Plan changes to shared Production resources
      run: bash ./cloud-infrastructure/environment/config/production.sh --plan

    - name: Plan changes to Production West Europe cluster
      run: bash ./cloud-infrastructure/cluster/config/production-west-europe.sh --plan

  production-environment-deploy:
    needs: production-plan
    runs-on: ubuntu-latest
    environment: 'production' ## Force a manual approval
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to the Production subscription
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_PRODUCTION }}

    - name: Deploy shared Production resources
      run: bash ./cloud-infrastructure/environment/config/production.sh --apply

  production-west-europe-deploy:
    needs: production-environment-deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to the Production subscription
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_PRODUCTION }}

    - name: Deploy Production West Europe cluster
      run: bash ./cloud-infrastructure/cluster/config/production-west-europe.sh --apply
