name: "Azure Infrastructure - Deployment"

on:
  push:
    branches:
    - main
    paths:
    - 'cloud-infrastructure/**'
  pull_request:
    branches:
    - main
    paths:
    - 'cloud-infrastructure/**'      
  workflow_dispatch:

jobs:
  shared-plan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install Bicep CLI
      run: |
        curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
        chmod +x ./bicep
        sudo mv ./bicep /usr/local/bin/bicep
        bicep --version
    - name: Login to the Shared subscription
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Plan changes to Shared resources
      env:
        CONTAINER_REGISTRY_NAME: ${{ vars.CONTAINER_REGISTRY_NAME }}
      run: bash ./cloud-infrastructure/shared/config/shared.sh --plan

  shared-deploy:
    if: github.ref == 'refs/heads/main' && needs.shared-plan.result == 'success'
    needs: shared-plan
    runs-on: ubuntu-latest
    environment: 'shared' ## Force a manual approval
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install Bicep CLI
      run: |
        curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
        chmod +x ./bicep
        sudo mv ./bicep /usr/local/bin/bicep
        bicep --version
    - name: Login to the Shared subscription
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Deploy Shared resources
      env:
        CONTAINER_REGISTRY_NAME: ${{ vars.CONTAINER_REGISTRY_NAME }}
      run: bash ./cloud-infrastructure/shared/config/shared.sh --apply

  staging-plan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install Bicep CLI
      run: |
        curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
        chmod +x ./bicep
        sudo mv ./bicep /usr/local/bin/bicep
        bicep --version
    - name: Login to the Staging subscription
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Plan changes to shared Staging resources
      run: bash ./cloud-infrastructure/environment/config/staging.sh --plan
    - name: Plan changes to Staging West Europe cluster
      env:
        ACTIVE_DIRECTORY_SQL_ADMIN_OBJECT_ID: ${{ vars.ACTIVE_DIRECTORY_SQL_ADMIN_OBJECT_ID }}
        CONTAINER_REGISTRY_NAME: ${{ vars.CONTAINER_REGISTRY_NAME }}
        UNIQUE_CLUSTER_PREFIX: ${{ vars.UNIQUE_CLUSTER_PREFIX }}
      run: bash ./cloud-infrastructure/cluster/config/staging-west-europe.sh --plan

  staging-environment-deploy:
    if: github.ref == 'refs/heads/main' && needs.staging-plan.result == 'success'
    needs: [shared-deploy, staging-plan]
    runs-on: ubuntu-latest
    environment: 'staging' ## Force a manual approval
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install Bicep CLI
      run: |
        curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
        chmod +x ./bicep
        sudo mv ./bicep /usr/local/bin/bicep
        bicep --version
    - name: Login to the Staging subscription
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Deploy shared Staging resources
      run: bash ./cloud-infrastructure/environment/config/staging.sh --apply

  staging-west-europe-deploy:
    if: github.ref == 'refs/heads/main' && needs.staging-environment-deploy.result == 'success'
    needs: staging-environment-deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install Bicep CLI
      run: |
        curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
        chmod +x ./bicep
        sudo mv ./bicep /usr/local/bin/bicep
        bicep --version
    - name: Login to the Staging subscription
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Deploy Staging West Europe cluster
      env:
        ACTIVE_DIRECTORY_SQL_ADMIN_OBJECT_ID: ${{ vars.ACTIVE_DIRECTORY_SQL_ADMIN_OBJECT_ID }}
        CONTAINER_REGISTRY_NAME: ${{ vars.CONTAINER_REGISTRY_NAME }}
        UNIQUE_CLUSTER_PREFIX: ${{ vars.UNIQUE_CLUSTER_PREFIX }}
      run: bash ./cloud-infrastructure/cluster/config/staging-west-europe.sh --apply

  production-plan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install Bicep CLI
      run: |
        curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
        chmod +x ./bicep
        sudo mv ./bicep /usr/local/bin/bicep
        bicep --version
    - name: Login to the Production subscription
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Plan changes to shared Production resources
      run: bash ./cloud-infrastructure/environment/config/production.sh --plan
    - name: Plan changes to Production West Europe cluster
      env:
        ACTIVE_DIRECTORY_SQL_ADMIN_OBJECT_ID: ${{ vars.ACTIVE_DIRECTORY_SQL_ADMIN_OBJECT_ID }}
        CONTAINER_REGISTRY_NAME: ${{ vars.CONTAINER_REGISTRY_NAME }}
        UNIQUE_CLUSTER_PREFIX: ${{ vars.UNIQUE_CLUSTER_PREFIX }}
      run: bash ./cloud-infrastructure/cluster/config/production-west-europe.sh --plan

  production-environment-deploy:
    if: github.ref == 'refs/heads/main' && needs.staging-west-europe-deploy.result == 'success'
    needs: [staging-west-europe-deploy, production-plan]
    runs-on: ubuntu-latest
    environment: 'production' ## Force a manual approval
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install Bicep CLI
      run: |
        curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
        chmod +x ./bicep
        sudo mv ./bicep /usr/local/bin/bicep
        bicep --version
    - name: Login to the Production subscription
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Deploy shared Production resources
      run: bash ./cloud-infrastructure/environment/config/production.sh --apply

  production-west-europe-deploy:
    if: github.ref == 'refs/heads/main' && needs.production-environment-deploy.result == 'success'
    needs: production-environment-deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install Bicep CLI
      run: |
        curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
        chmod +x ./bicep
        sudo mv ./bicep /usr/local/bin/bicep
        bicep --version
    - name: Login to the Production subscription
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Deploy Production West Europe cluster
      env:
        ACTIVE_DIRECTORY_SQL_ADMIN_OBJECT_ID: ${{ vars.ACTIVE_DIRECTORY_SQL_ADMIN_OBJECT_ID }}
        CONTAINER_REGISTRY_NAME: ${{ vars.CONTAINER_REGISTRY_NAME }}
        UNIQUE_CLUSTER_PREFIX: ${{ vars.UNIQUE_CLUSTER_PREFIX }}
      run: bash ./cloud-infrastructure/cluster/config/production-west-europe.sh --apply
